### ISSUE TITLE
Add support for Angular 1.5

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#13]
Allow framework to be compatible with angular 1.5, without dropping support for 1.3 or 1.4

**Comment by tolyo** [comment]
I am working with 1.5 and haven't encountered any issues thus far.

**Comment by soumak77** [comment]
Updating to 1.5 causes the tests to fail: https://travis-ci.org/base-apps/angular-base-apps/builds/145319822

**Comment by tolyo** [comment]
I'll take a look at that

**Comment by tolyo** [comment]
Fixed
