### ISSUE TITLE
Remove $foundation-version scss variable

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#15]
Is anyone aware of the usage of the `$foundation-version` SCSS variable in the codebase?  I see the comment "Meta styles are included in all builds, as they are a dependency of the Javascript.", however, only `foundation-mq` is used.

I'll remove it if it is not used, otherwise, the build will need to be updated to auto update the version with each build.

**Comment by soumak77** [comment]
@gakimball @AntJanus would either of you be able to provide insight on this?

**Comment by gakimball** [comment]
@soumak77 As I recall it was mostly a Sass equivalent of the JavaScript variable `Foundation.VERSION`, although that has a more practical debugging purpose (and lets you open a console and see what version of Foundation a site is using).

For Apps, I don't believe it does anything, so you're free to remove it.

**Comment by soumak77** [comment]
@gakimball thanks for the insight, it'll be removed
