### ISSUE TITLE
Remove reference to foundation in all files

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#31]
Remove references to all foundation modules and files.  This release will require developers use the new `base` modules and distro files as defined in the [1.2.1 release](https://github.com/base-apps/angular-base-apps/releases/tag/v1.2.1).
- [x] replace `zf` references with `ba` (in framework and docs)
- [x] remove `foundation` modules
- [x] remove `foundation` distro files
- [x] remove `foundation` in docs
- [x] replace `foundation` in code base (https://github.com/base-apps/angular-base-apps/pull/44)

**Comment by soumak77** [comment]
@tolyo do you have a preference on whether we use prefix `ab` for angular base or `ba` for base apps?

**Comment by tolyo** [comment]
@soumak77 not really.... in one case its Angular Base and in another its Base Apps....

**Comment by soumak77** [comment]
@tolyo I'll go with `ba` so that the prefix can be used across any projects created by the Base Apps org

**Comment by soumak77** [comment]
Basic renaming is complete.  Now the following angular services and factories need to be renamed:
- `FoundationApi`
- `FoundationAdapter`
- `FoundationMQ`
- `FoundationMQInit`
- `FoundationAnimation`
- `FoundationActionSheet`
- `FoundationModal`
- `FoundationNotification`
- `FoundationOffcanvas`
- `FoundationPanel`
- `FoundationPopup`
- `FoundationTabs`

And the following SCSS variables:
- `$foundation-colors`

I don't like the naming `BaseApi` because it's too generic.  I'm thinking to use the word `BaseApps` to replace the word `Foundation` in the javascript codebase and `base-apps` to replace the word `foundation` in the SCSS codebase.
