### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#35]
With most of the framework stabilized as of v1.2.5, I'm looking for what to work on next for this framework.  If anyone has opinions on new features or enhancements to existing ones, let's talk about it!  Here are the current approved features:
### Loading Symbols (https://github.com/base-apps/angular-base-apps/issues/38) (v2.0)

A set of loading symbol directives that make it easy to change the style and color of the loading symbol.  The directive should work flawlessly with `ng-if`, `ng-show`, and `ng-hide` to allow controlling the visibility of the symbol (i.e. show when loading data, hide when data is loaded).

I'm thinking this library would be cool to integrate: http://tobiasahlin.com/spinkit/
### Confirm Modal (https://github.com/base-apps/angular-base-apps/issues/39) (v1.2.6)

A directive to replace `window.confirm`.  The directive would be built using a modal and allow for an asynchronous confirmation in the app.  Various SCSS variables can be exposed to allow styling of the confirmation modal.
### Prompt Modal (https://github.com/base-apps/angular-base-apps/issues/40) (v1.2.6)

A directive to replace `window.prompt`.  The directive would be built using a modal and allow for an asynchronous prompt in the app.  Various SCSS variables can be exposed to allow styling of the confirmation modal.
### Replace Font Iconic (https://github.com/base-apps/angular-base-apps/issues/37) (v2.0)

Its a commercial webfont and icon set and including its free parts is plain advertising. Two great replacement options are either [Ionicons](http://ionicons.com/) or Android [icons](https://design.google.com/icons/). Either choice will be a much better feature for us.
### Animating Views (https://github.com/base-apps/angular-base-apps/issues/42) (v2.0)

Does anybody actually use them? Its not valid HTML, it belongs in route definitions and if necessary, it can be moved to a separate directive. Do we need them?

**Comment by soumak77** [comment]
While using this framework I've had to build out various features on my own that might be useful to integrate into the core framework.  Here are a summary of those features:

### No Support Detection

If the framework is not supported by the browser, display an overlay indicating lack of support.

Currently I use Modernizr's flex-box support as the way for determining whether the framework is supported.  With Modernizr's automated custom build, the size of the additional dependencies for this feature can be minimized.

### Loading Symbols

A set of loading symbol directives that make it easy to change the style and color of the loading symbol.  The directive should work flawlessly with `ng-if`, `ng-show`, and `ng-hide` to allow controlling the visibility of the symbol (i.e. show when loading data, hide when data is loaded).

I'm thinking this library would be cool to integrate: http://tobiasahlin.com/spinkit/

### Confirm Modal

A directive to replace `window.confirm`.  The directive would be built using a modal and allow for an asynchronous confirmation in the app.  Various SCSS variables can be exposed to allow styling of the confirmation modal.

### Prompt Modal

A directive to replace `window.prompt`.  The directive would be built using a modal and allow for an asynchronous prompt in the app.  Various SCSS variables can be exposed to allow styling of the confirmation modal.

The prompt could be configured to use a text input, numerical input, or drop down.

### Authentication and Route Security

Allow blocking access to certain routes based on the app's authentication.  The blocking of access to a state is trivial with `ui-router` and simply needs to be configured per the requirements of the app.  A front-matter configuration option could be added to enable authentication checks for a state.  

The following criteria are useful when needing to filter access:
- authenticated
  - Whether or not user is authenticated.  Give access if authenticated, otherwise don't.
- user names
  - A white list of user names that have access.
- roles
  - A white list of user roles that have access.
- custom
  - A custom check for whether the user has access.

### Versioning

Every app needs a version!  I use an angular constant to store the version of my apps so I can reference it through the app as needed.  This constant is auto generated at build time and is based on the bower.json and package.json version.  A gulp plugin (like the dynamic router) can be created to enable a drop-in implementation of the application version.

This feature should be used in the documentation build for this framework so that the latest version doesn't need to be manually updated throughout the docs with every build.

**Comment by mattgrande** [comment]
Hey @soumak77, I just wanted to thank you for your work on this thus far. I want to contribute, but I don't currently have the time, but I really like the direction it's headed. Thanks.

**Comment by tolyo** [comment]
@soumak77 Awesome work Brian. 
For route and auth security, I currently use [Angular Permission](https://github.com/Narzerus/angular-permission). Its quite good. My two cents:

### Replace Font Iconic

Its a commercial webfont and icon set and including its free parts is plain advertising. Two great replacement options are either [Ionicons](http://ionicons.com/) or Android [icons](https://design.google.com/icons/). Either choice will be a much better feature for us.

### Animating Views

Does anybody actually use them? Its not valid HTML, it belongs in route definitions and if necessary, it can be moved to a separate directive. Do we need them?

**Comment by soumak77** [comment]
@tolyo I would really love to figure out how to get the same functionality for animating views to work with animating any html (this might be possible and just not in the docs).  For instance, on almost a daily basis I find myself writing something like:

``` html
<div ng-if="value">
</div>
<div ng-if="!value">
</div>
```

I would like to be able to smoothly animate the two elements when the `value` changes.  I know I can use the ui-motion classes, but the two elements don't animate in unison.

Also, I like the idea of being able to drop in other icon libraries, however, I don't want to drop support for Iconic.  I use it in my business applications and I don't want to have to change that just to keep up-to-date with this framework.  We can build an icon manager that supports multiple icon libraries and allow developers to pick which one(s) they want to use.  I'm not sure how integration works for other icon libraries, but I'm sure the logic can be wrapped in a single directive to match the functionality of `zf-iconic`.

**Comment by tolyo** [comment]
@soumak77 Isn't `$animate` designed to address that use case? Css-transitions requires some tinkering to work smoothly but its doable.

**Comment by soumak77** [comment]
@tolyo I'm not familiar enough with `$animate`, but I believe that is what is used under the hood for view animations.  Last I checked it only worked on elements with a `ui-view` attribute.  I don't know how to make it work for generic html.

**Comment by tolyo** [comment]
@soumak77 Synchronization of animation for different components is not trivial issue. Not sure where even to begin.

**Comment by soumak77** [comment]
@tolyo I just looked at the implementation for view animation and it does not use `$animate`.  It attempts to re-use the Motion UI classes to make the animations work smoothly.  I like the intent as it would make it very easy to flag which content that should be animated without having to do all the heavy lifting.

If a similar design can be created that uses `$animate` I would like to explore that.  I feel there is a lot of boilerplate code that the framework can provide, just not sure where the framework should stop and the application pickup.  At the most basic the developer just needs to add a few classes/attributes to define the animation between two components.  Not sure it's that simple though.

**Comment by soumak77** [comment]
@tolyo @mattgrande I created a milestone for the next [1.3 release](https://github.com/base-apps/angular-base-apps/milestone/1).  Let me know if you have any other features you would like to see added in that release.  

I would like to publish 1.3 near the end of the month if possible, but wouldn't mind hold off to add some cool features.

**Comment by soumak77** [comment]
https://github.com/base-apps/angular-base-apps/issues/31 will result in a lot of breaking changes, so the next release will be 2.0

**Comment by soumak77** [comment]
I'm going to close this, but continue to contribute ideas via new issues!
