### ISSUE TITLE
Loading Symbol Directives

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#38]
Create a set of loading symbol directives that make it easy to change the style and color of the loading symbol.  The loading symbols from [SpinKit](http://tobiasahlin.com/spinkit/) would be a good place to start.  All the loading symbols are created with SCSS and will plug in nicely with this framework.

**Comment by soumak77** [comment]
One thing I noticed is that SpinKit does not provide SCSS mixins, so changing the size of the loading symbol is not supported.  I've created an issue to track adding of SCSS mixins to the library (https://github.com/tobiasahlin/SpinKit/issues/120).  Once that is implemented it should be fairly straight forward to get the directives created.

**Comment by soumak77** [comment]
I finished rewriting the spinkit library to use mixins (tobiasahlin/SpinKit#121).  There appears to already be a library though that is attempting to do what I want: https://github.com/Urigo/angular-spinkit.  I'll contact the author to see if they are willing to update their library to be responsive.

**Comment by soumak77** [comment]
On second thought, since the integration is so simple, I would prefer to fully integrate the library into the framework.  This way the spinners can be easily colored and sized similar to everything else in the framework.

Anyone else have input on this?

**Comment by tolyo** [comment]
@soumak77 Integrate into the library for fewer dependencies.

**Comment by soumak77** [comment]
Done. I've included the modified source code from SpinKit with the framework until https://github.com/tobiasahlin/SpinKit/pull/121 is accepted and a new version is published.
