### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#5]
I was having the strangest bugs appear in my apps only on certain devices and couldn't for the life of me figure out what was going wrong.  I then stumbled upon this line of code in the build:

``` javascript
.pipe($.autoprefixer({
  browsers: ['last 2 versions', 'ie 10']
}))
```

Recent browser releases have changed what this code actually does and therefore which browsers are actually supported by the framework.  In my local build I've updated this to the following:

``` javascript
.pipe($.autoprefixer({
  browsers: ['> 1%', 'last 2 versions', 'ie >= 10', 'iOS >= 7', 'Safari >= 7', 'Opera >= 25', 'not ie <= 9']
}))
```

This should match the exact list provided in the [compatibility docs](http://foundation.zurb.com/apps/docs/#!/compatibility) regardless of future releases of any browser.  Evergreen browsers such as firefox and chrome will autoupdate the user's browser automatically, so the first two checks should cover those browsers.

**Comment by AntJanus** [comment]
I think we can go ahead and make that fix in the repo.

**Comment by soumak77** [comment]
It appears the `not` query syntax is only supported in gulp-autoprefixer >= 3.x, which removes support for node 0.10.x and causes failures during testing.  I'll remove the `not ie <= 9` from the list so we don't need to worry about changing node versions.
