### ISSUE TITLE
[Doc] Update the changelog page

### ISSUE THREAD

**Issue by Seb-** [base-apps/angular-base-apps#50]
https://base-apps.github.io/angular-base-apps/#!/changelog

I'm currently considering to migrate from foundation-apps to angular-base-apps but a properly updated changelog would help a lot to understand the changes between the two.

I want to know what I'll get, and if it is actually an interesting move to make.

The main question I am wondering are:
- Is it a drop in replacement? It very much seems to be (up to 1.2.6) but it's hard to find a definitive answer. If not (or when 2.0 comes), where is the migration guide?
- What bugfixes am I getting with it?
- Any new features?
- Is that doc even up to date? There is no date or version. What version is targeted by the doc? Changelog page indicates 1.2 (no change), while CND links seem to indicate 1.2.6. Readme says it's latest release, confirming it.

So I could find the answer to most questions by browsing around, eg. #9, #35, tags history, readme. But this is not ideal.

**Comment by soumak77** [comment]
@Seb- Thanks for taking interest in this fork!  I admit the changelog needs some work which I'll hopefully get to soon, but for now here is the info you're looking for:
- Version 1.2.x is a drop in replacement for Foundation for Apps and contains the following fixes/features
  - https://github.com/base-apps/angular-base-apps/pull/3 (feature) -  Add `base.*` modules to replace `foundation.*` modules in future **(1.2.1)**
  - https://github.com/base-apps/angular-base-apps/pull/14 (fix) -  Most of the pending PRs from Foundation for Apps **(1.2.2)**
  - #21 (fix) - Allow links inside modals to be clickable **(1.2.3)**
  - https://github.com/base-apps/angular-base-apps/pull/30 (fix) - Fix tabs component  **(1.2.4)**
  - https://github.com/base-apps/angular-base-apps/pull/34 (fix) - Fix accordion component **(1.2.5)**
  - https://github.com/base-apps/angular-base-apps/pull/41 (feature) - implementation of confirm and prompt modals **(1.2.6)**
- Docs are for the latest releast which is version 1.2.6
- Version 2.0 removes all references to foundation and will be completely separated from ZURB. The migration guide is already written and is part of the installation docs.  Run the docs locally to see those changes.
  - #16 (feature) - Added destroy-on-close property to modals
  - #31 (feature) - Remove `foundation` from entire codebase
  - #38 (feature) - Loading Symbols
  - #37 (feature) - Refactored icons into new [angular-icons](https://github.com/base-apps/angular-icons) library
  - #42 (feature) - decoupled dynamic routing into [angular-dynamic-routing](https://github.com/base-apps/angular-dynamic-routing) and the gulp task into [angular-front-router](https://github.com/base-apps/angular-front-router)

**Comment by soumak77** [comment]
Changelog has been updated for 1.2.x and 2.0.0
