### ISSUE TITLE
[Doc] Buttons bring back to the homepage

### ISSUE THREAD

**Issue by Seb-** [base-apps/angular-base-apps#51]
https://base-apps.github.io/angular-base-apps/#!/button

When clicking on buttons (any of them, except those under Segmented Button Group and Input Groups) we are back to the homepage.

This is pretty annoying. It would be better to do nothing instead, so the user can test the behaviour and the different (CSS) states of clicking on a button.

Open to debate. It could be argued that it is better this way since a real button will usually lead to another page.

**Comment by soumak77** [comment]
I agree, the buttons should do nothing
