### ISSUE TITLE
[Popup/Notification] Having a popup/notification open prevents changing page

### ISSUE THREAD

**Issue by Seb-** [base-apps/angular-base-apps#53]
https://base-apps.github.io/angular-base-apps/#!/popup
- click on the popup example
- while the popup is open, click on a link on the menu
- nothing happens

The same issue is there with notifications.

https://base-apps.github.io/angular-base-apps/#!/notification

While it can be argued that modals should display this behaviour, I don't think it's great for popups and especially not for notifications.

**Comment by Seb-** [comment]
Depending on the changes required to fix this, it would be even better to leave is as an option.

**Comment by soumak77** [comment]
@Seb- the root cause was a bug inside `baCloseAll`.  As such, it won't be a quick fix to make the option configurable.
