### ISSUE TITLE
Update from Zurb 18 Aug 2016

### ISSUE THREAD

**Issue by jmpreston** [base-apps/angular-base-apps#54]
I talked to Zurb’s lead engineer yesterday evening at a Meetup at Zurb.  Foundation for Apps is deprecated, although not officially, yet.  The people who were working on it left the company about a year ago.  They are discussing making Foundation for Sites plug-ins for Angular, Ember, and React but development is sometime in the future, at least a year away.   There is a plugin for Angular 1 done by someone outside the company.

Zurb’s main product for their clients is design and they deliver 5 html pages with a style guide.  They don’t seem to be developing single page apps and didn’t discuss that during the Meetup.  They are looking for someone to head up their Foundation projects.

Hope this information is useful.  Big thank you to those contributing to this project!!!

**Comment by soumak77** [comment]
@svstartuplab thanks for the notes Jim!  I figured as much, but it would have been nice for someone from ZURB to provide those details over the last year, especially if they are still promoting their framework.  That level of professionalism is unacceptable from their end.  At least there is now an alternative for those that get stuck with Foundation for Apps.
