### ISSUE TITLE
ModalFactory activate does not show dialog anymore

### ISSUE THREAD

**Issue by cjh79** [base-apps/angular-base-apps#66]
I'm using angular-base-apps v. 1.2 which I downloaded via bower. (I just switched from Foundation for Apps). When I use ModalFactory to create a dialog, and then call its activate() method, the dialog does not appear.

The modal-overlay div element is being appended to the body properly, but it does not get the 'is-active' class, so it remains hidden.

I suspect the issue was introduced in this commit but am not certain as I have not been able to track down the bug:
https://github.com/base-apps/angular-base-apps/commit/09eff9fc2677911160398f75ffc3e8f400062ae9

Happy to help with a fix if possible, but someone who knows the code can probably do a better job of this.

**Comment by soumak77** [comment]
@cjh79 which exact version are you using?  The `1.2.7-*` versions are prereleases for 2.0 and you would need to follow the [migration steps](http://base-apps.github.io/angular-base-apps/latest/#!/migration) before using those versions.  Try out version `1.2.6` as a drop-in replacement and let me know if you still have this issue.

**Comment by cjh79** [comment]
@soumak77 I'm using 1.2.6.

**Comment by soumak77** [comment]
@cjh79 do you have a code snippet?  I've been using `1.2.6` in production and haven't seen any such issues with modals.

**Comment by soumak77** [comment]
@cjh79 modals in the 1.2.6 docs use `activate` and are working: http://base-apps.github.io/angular-base-apps/v1.2.6/#!/modal

I'll take a look at your code snippet to see if I can figure anything out.

**Comment by cjh79** [comment]
@soumak77 I see the issue with this html file. The modal-overlay element is appended to body, but does not get the is-active class and has display: none.

```
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <link rel="stylesheet" href="http://cdn.jsdelivr.net/angular-base-apps/1.2.6/base-apps.css">
    <script src="http://cdn.jsdelivr.net/angular-base-apps/1.2.6/base-apps.js"></script>
    <script src="http://cdn.jsdelivr.net/angular-base-apps/1.2.6/base-apps-templates.js"></script>
</head>

<body ng-app="testApp" ng-controller="testAppController">

<script type="text/javascript">
    (function() {
        angular.module('testApp', [
            'foundation',
            'foundation.modal'
        ]);
        angular.module('testApp').controller('testAppController', ['ModalFactory', function(ModalFactory) {
            var modal = new ModalFactory({
                template: '<h1>the dialog</h1>'
            });
            modal.activate();
        }]);
    })();
</script>
</body>
</html>
```

**Comment by soumak77** [comment]
ModalFactory does not have a `template` property.  It only has a `templateUrl` property.

**Comment by cjh79** [comment]
@soumak77 FWIW, template seems to work, nevertheless, I just did that to simplify the code -- I see the same issue when using templateUrl.

**Comment by soumak77** [comment]
@cjh79 could you possibly try wrapping `model.activate()` in a `$timeout`?

Also, you said this example works with Foundation for Apps?

**Comment by cjh79** [comment]
Wrapping it in a $timeout did not help. Yes, it was working fine in Foundation for Apps.

**Comment by soumak77** [comment]
I found the problem.  The templates were mistakenly updated to use the `base` module (see https://cdn.jsdelivr.net/angular-base-apps/1.2.6/base-apps-templates.js):

```
angular.module('base').run(['$templateCache', function($templateCache) {
```

Try replacing `foundation` with `base` and `foundation.modal` with `base.modal`.

**Comment by soumak77** [comment]
The root cause of this issue has been captured by https://github.com/base-apps/angular-base-apps/issues/67

**Comment by cjh79** [comment]
That fixed it. Excellent, thanks!
