### ISSUE TITLE
Merge distro files

### ISSUE THREAD

**Issue by tolyo** [base-apps/angular-base-apps#69]
@soumak77 I am looking at the templates distribution file and it is only 350 lines long unminified. Is there a reason why it remains separate from the main distro?

**Comment by soumak77** [comment]
@tolyo It provides the ability to optionally not preload the `$templateCache`.  So if you want to host the templates yourself, the app will only download the templates when needed and then store them in the cache.  With such a small template library as of now that is probably not an issue, but that may not be true in the future.

**Comment by tolyo** [comment]
@soumak77 But there are no templates for hosting in `dist`. In essence they are components and would be written as Angular components if we were to ignore backwards compatibility, which is all the more the reason to include them in the main dist. The separation is confusing to a newcomer and becomes even more odd after sufficient familiarity with the framework.

**Comment by soumak77** [comment]
@tolyo I'm okay with combining the files.  If someone is in need of a more advanced configuration, they'll likely be building from source anyway.

**Comment by tolyo** [comment]
@soumak77 Agreed

**Comment by soumak77** [comment]
@tolyo can you also update the install and migration docs?

**Comment by tolyo** [comment]
@soumak77 Will do
