### ISSUE TITLE
Child view not working

### ISSUE THREAD

**Issue by mkriskovic-r7** [base-apps/angular-base-apps#75]
Using angular-base-apps v2.0.0, base-apps-router installed, angular-dynamic-routing installed. Have the two following .html files:

``` html

---
name: pulse
url: /pulse
controller: PulseController

---
```

and

``` html

---
name: pulse.question
url: /question
controller: PulseQuestionController

---
```

The Question keeps routing to the parent 'Pulse' page. No JS errors. No compile errors.

Been through the instructions several times and don't seem to be missing any steps. Can anyone verify that this is working in their local branch w/ version 2.0.0?

Thanks!
~Michael

![screenshot 2016-09-01 14 08 31](https://cloud.githubusercontent.com/assets/14186098/18184389/bac68710-704d-11e6-94d8-61d1ecf1dc50.png)

**Comment by soumak77** [comment]
@mkriskovic-r7 looks like you're missing the [ui-view](https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views#nested-states--views) attribute.  Adding the following inside `pulse.html` should fix that.

``` html
<div class="grid-block" ui-view>
</div>
```

**Comment by mkriskovic-r7** [comment]
You are absolutely right, @soumak77! Thank you! I didn't realize there would need to be another ui-view here to accommodate the child views but it totally makes sense. Might be a good idea to add to the README.md file in the [https://github.com/base-apps/base-apps-router](https://github.com/base-apps/base-apps-router) repo. I will make a PR for that.

**Comment by soumak77** [comment]
@mkriskovic-r7 glad to help!
