### ISSUE TITLE
Implement Foundation-Apps-Modal tools

### ISSUE THREAD

**Issue by gfviegas** [base-apps/angular-base-apps#79]
Hi, I was using Found for Apps, and I found this plugin : https://github.com/ivnivnch/foundation-apps-modal which gives us a great tool to bind Controllers to modal and it's way more angular-friendly, as it returns promises. Can we natively integrate the tools of this plugin into Base-Apps?

It would be great to see the modal improved, or at least help the plugin to migrate to Base-Apps. I've opened an issue in their repo as well: https://github.com/ivnivnch/foundation-apps-modal/issues/8

**Comment by soumak77** [comment]
@gfviegas have you tried using the `ba-advise` directive mentioned in the [docs](http://base-apps.github.io/angular-base-apps/latest/#!/angular-modules)?  This directive provides notification support for various states of a component and can be used for more than just modals.  This directive is arguable more powerful than promises as you can hookup callbacks in multiple places of your code and not just the one place you created the modal.

**Comment by soumak77** [comment]
I do see though that `ModalFactory` does not currently support adding the `ba-advise` attribute to the dynamically created modal.  Issues https://github.com/base-apps/angular-base-apps/issues/80 has been created to track that.

**Comment by soumak77** [comment]
@gfviegas try with [v2.0.4](https://github.com/base-apps/angular-base-apps/releases/tag/v2.0.4) and let me know if you can achieve what you're looking to do

**Comment by gfviegas** [comment]
@soumak77 another GREAT feature is to use the Controller to link to modal. What the plugin does is basically adapt the ZFA modal to be a little bit like AngularUI Bootstrap Modal.. See https://angular-ui.github.io/bootstrap/

This way we can create stateful modals, and put the modal logic in its own file.

**Comment by soumak77** [comment]
@gfviegas You should be able to accomplish what you need with the `contentScope` config property of the `ModalFactory`

**Comment by gfviegas** [comment]
@soumak77 Can I link a controller name into the contentScope?

**Comment by soumak77** [comment]
@gfviegas no that is not currently possible

**Comment by gfviegas** [comment]
@soumak77 that's what I was referring to. So for me it's missing 2 big functionalities that exists in the plugin I linked:
- Resolve the modal with a success data or dismissing it with a error data promise-like.
- Bind a modal to a Controller.

**Comment by soumak77** [comment]
I wouldn't be opposed to having the `ModalFactory` return promises for the following methods:
- activate
- deactivate
- toggle

Currently those methods don't return anything, so having them return a promise won't break backwards compatibility.

Support can also be added to the `ModalFactory` to allow providing a `controller` instead of a `contentScope`.

Feel free to submit PRs for either of those features.

**Comment by gfviegas** [comment]
I dont really know how the source works, but I'll study and submit my PR. For now, I asked help for the plugin creator so we can have more resources to work on top of it.. Thanks bro @soumak77 !

**Comment by soumak77** [comment]
@gfviegas I'm going to close this but feel free to add a PR for the desired support
