### ISSUE TITLE
SCSS fails to compile in existing project

### ISSUE THREAD

**Issue by bachle** [base-apps/angular-base-apps#82]
I have an existing angular project using the yeoman angular generator. After installing angular base apps, the scss files will not compile and throwing an error. The compiler being used is compass. 

> Error: $original: \".\" is not a valid selector: Invalid CSS after \".\": expected class name, was \"\" for `selector-replace'\A on line 26 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/vendor/spinkit/spinners/4-wandering-cubes.scss, in`sk-wandering-cubes-animation'\A from line 49 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/helpers/_loaders.scss, in `size-loaders'\A from line 93 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/components/_button.scss, in`button-size'\A from line 283 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/components/_button.scss, in `button'\A from line 290 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/components/_button.scss, in`@content'\A from line 49 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/helpers/_functions.scss, in `exports'\A from line 288 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/components/_button.scss\A from line 30 of /Users/test/Code/starter/node_modules/angular-base-apps/scss/base.scss\A from line 4 of /Users/test/Code/starter/app/styles/main.scss";
> }

any ideas?

**Comment by tolyo** [comment]
@bachle can we see your `package.json` and your sass build step?

**Comment by soumak77** [comment]
@bachle Looks like there is a bug in the usage of the [selector-replace](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_replace-instance_method) method on [line 26 of 4-wandering.cubes.scss](https://github.com/base-apps/angular-base-apps/blob/master/scss/vendor/spinkit/spinners/4-wandering-cubes.scss#L26).

```
$original: \".\" is not a valid selector
```

Not sure why compass is tripping on this usage.  To get around this error you can disable the exporting of the loader CSS in the settings file: https://github.com/base-apps/angular-base-apps/blob/master/scss/_settings.scss#L56

**Comment by bachle** [comment]
It looks like switching from compass to libsass fixed it for me. Gonna close.
