### ISSUE TITLE
baCloseAll can cause modal dialogs to close immediately after opening 

### ISSUE THREAD

**Issue by cjh79** [base-apps/angular-base-apps#85]
When using baCloseAll, clicking on an element that is a descendant of a ba-open/ba-close (etc.) element does not open the thing that is supposed to be opened.

[This jsfiddle](https://jsfiddle.net/82g6yu6f/) shows the bug.

Before closing active dialogs etc., the baCloseAll directive looks for a ba-close/ba-open/ba-toggle attribute and doesn't close everything if it finds it on the element. However, it does not check the element's ancestry. It seems that it ought to. If others agree that this is how it should work, I have a fix that I would be happy to test further and then create a pull request for.

Adding the open/close attribute to all contained elements is a workaround, but is not always possible, for instance if there are generated elements within the element.

**Comment by soumak77** [comment]
@cjh79 That fix sounds good.  Submit a PR and I'll take a look.
