### ISSUE TITLE
Pending releases

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#9]
Conversation was started on #1, but the thread has grown to include topics that shouldn't be in the initial release.  I want to ensure we are all on the same page in terms expectations for upcoming releases.  Here is what I'm thinking so far and will update these requirements as needed:
- **Release 1.2.1** (Rebranding)
  - **Description**
    - Drop in replacement for Foundation for Apps 1.2.  No changes should be required to consume this version.
    - Documentation for the release will still leverage [Foundation for Apps docs](http://foundation.zurb.com/apps/docs/#!).
  - **TODO**
    - [x] Merge [rebanding branch](https://github.com/base-apps/angular-base/tree/feature/rebrand) into master
    - [x] Add gulp task to publish new version of distro files to github and tag them with the version
      - basically copy/paste example from [gulp-tag-version](https://www.npmjs.com/package/gulp-tag-version) and trigger after running build
    - [x] Publish NPM/Bower packages
  - **PRs**
    - [x] #2
    - [x] #5
    - [x] #8
    - [x] #10
    - [x] #12
- **Release 1.2.2** (Bug Fixes and Documentation)
  - **Description**
    - Bug fixes on top of the 1.2.1 release.  Minimal changes may or may not be required to consume this version.  
    - Documentation for this release will be fully migrated to [github pages](https://base-apps.github.io/angular-base-apps).
  - **TODO**
    - [x] Discuss changes to documentation: https://github.com/base-apps/angular-base/issues/4
    - [x] Create new PRs for fixes in old fork: https://github.com/zurb/foundation-apps/pulls
- **Release 1.2.3** (Bug Fixes)
- **Release 1.2.4** (Tabs Fixes)
  - Improved tab functionality and documentation

**Comment by soumak77** [comment]
@tolyo I see you marked #8 as completed, but it must still be merged to master

**Comment by soumak77** [comment]
I meant #3

**Comment by tolyo** [comment]
`Rebranding` merged to `master`

**Comment by soumak77** [comment]
@tolyo I'm hoping to get back to this in a couple days.  I'd like to publish the first release this weekend.

**Comment by tolyo** [comment]
@soumak77 np

**Comment by soumak77** [comment]
Version 1.2.1 has been published.  Unfortunately the name `angular-base` is taken in the bower registry by [this repo](https://github.com/carlospliego/angular_base).  I've registered the package under `angular-base-apps`.  I originally published the npm package under `angular-base`, but then switched to `angular-base-apps` to be consistent with bower.

**Comment by tolyo** [comment]
Brian, I say we rename the git repo too.

**Comment by soumak77** [comment]
@tolyo yeah that would probably be for the best.  I'll do that now and re-register the new repo with bower and npm.

**Comment by soumak77** [comment]
I wasn't able to unregister/register the package on bower, so I opened [an issue on bower](https://github.com/bower/registry/issues/209)

**Comment by tolyo** [comment]
@soumak77 Brian, how would we go about other people's pull requests? Is that something we can migrate or is that something we would have to go through one by one?

**Comment by soumak77** [comment]
@tolyo this has already been completed with https://github.com/base-apps/angular-base-apps/pull/14

**Comment by tolyo** [comment]
@soumak77 Ok. I guess we still need to monitor for them as people keep creating them for `zurb:master`

**Comment by soumak77** [comment]
Version 1.2.2 has been published

**Comment by soumak77** [comment]
I've creating separate issues for the remaining items so that this can be closed.
