### ISSUE TITLE
Angular 2 layout engine

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#90]
I'm working with angular 2 and started using [Material Design](https://material.angular.io).  One major feature missing from the material design framework is how to generate a nice layout.  They suggest [angular flex layout](https://github.com/angular/flex-layout), however I disagree with the design in how all sizing must be specified in the html versus style sheets.  Does anyone know of a good layout engine for angular 2?

I really like how angular base apps makes it simple to generate layouts using the [grid](http://base-apps.github.io/angular-base-apps/latest/#!/grid).  The interchange directives and visibility classes are also a great help in making it easy to generate responsive layouts.  If I can't find a layout engine I like I might consider creating an angular 2 version of this framework to help with responsive design on top of using angular's material design.

**Comment by tolyo** [comment]
@soumak77 There is a layout API in [Angular Material](https://material.angularjs.org/latest/layout/container) and I would expect them to have a similar feature for the second version.

**Comment by tunecino** [comment]
I don't know much about angular 2 as I'm just starting to learn it but if I have to start from scratch following angular 2 way to build features I'd check [bulma.io](http://bulma.io/) and [picnicss.com](http://picnicss.com/) as both are modern lightweight css-only frameworks with native flex support. If anyone have ideas on how angular-base-apps should be best restructured to work on an optimized way with angular 2 please share.

**Comment by soumak77** [comment]
@tolyo I believe they are pushing for [angular/flex-layout](https://github.com/angular/flex-layout) to be the layout API for angular 2 (see bottom of [material 2 feature list](https://github.com/angular/material2#project-status)).  The problem I have is that every example has the styling being done via html attributes instead of css classes.  So when you have any responsive styling provided via CSS (i.e. the material 2 framework), your html must account for it.  This seems like a bad design approach and won't work well for large scale applications.

flex-layout does provide the functionality I want, I just don't like the interface they designed to use the framework.  The examples they provide are not realistic so it makes it difficult to figure out how to use the framework on a larger scale.

**Comment by tolyo** [comment]
@soumak77 I see. Yes it looks like they are trying to solve a non-existent problem with those attributes. For version 2 of the framework, I would like to see a more [BEM](https://en.bem.info/)ish approach to component styling use. Its being used in MDLite and lends itself well to component design.
