### ISSUE TITLE
Creative usage of selector-replace() in 4-wandering-cubes.scss throws error on libsass 3.5.0.beta.2

### ISSUE THREAD

**Issue by chadbrogan** [base-apps/angular-base-apps#91]
This issue was already reported as a problem with compass (#88 ).

Compiling with latest version of node-sass on windows 7 . . . 

```shell
$ node_modules/.bin/node-sass -v
node-sass       4.5.2   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```
generates the following error:

```shell
$ node_modules/.bin/node-sass node_modules/angular-base-apps/scss/base.scss > blah.css
{                                                                                                                         
  "status": 1,                                                                                                            
  "file": "[SELECTOR]",                                                                                                   
  "line": 1,                                                                                                              
  "column": 1,                                                                                                            
  "message": "Invalid CSS after \"\": expected selector, was \"\"",                                                       
  "formatted": "Error: Invalid CSS after \"\": expected selector, was \"\"\n        on line 1 of [SELECTOR]\n>> \n   ^\n" 
}
```

`selector-replace` method used in 4-wandering-cubes.scss -> `@mixin sk-wandering-cubes-animation(...)` expects the $replacement parameter to be non-empty.

```scss
  $keyframeName: selector-replace("sk-wanderingCube-" + $width + "-" + $height, ".", "");
```
Is this code trying to find/replace `.` inside the `$width` and `$height` vars? If so, would a custom find/replace method be a better fit?

**Comment by soumak77** [comment]
@chadbrogan is your app using loading symbols?  If not you can disable the component by setting the following variable in your `_settings.scss` file to `false`: https://github.com/base-apps/angular-base-apps/blob/master/scss/_settings.scss#L56

If you want to use the loading symbols, you are free to offer up a PR with the desired changes to make it compile.  This code was taken directly from https://github.com/tobiasahlin/SpinKit, so I don't have an immediate answer for how to fix this issue.

**Comment by chadbrogan** [comment]
@soumak77 An option for disabling the spinkit module was what I was looking for (it's not used in our app). Thank you.

If anyone else runs into this and needs a very hacky workaround, you can also override the selector-replace method. Again very hacky, but it compiled on my machine:

```scss
@function selector-replace($string, $search, $replace: '') {
  $index: str-index($string, $search);

  @if $index {
    @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
  }

  @return $string;
}
````

**Comment by Maximaximum** [comment]
Thanks god I've found this bug reported here. I would've never found this out by my own!

Though, I still don't really get what's going on here and why do I get that weird `[SELECTOR]` error
