### ISSUE TITLE
Auto-close action sheet

### ISSUE THREAD

**Issue by cjh79** [base-apps/angular-base-apps#94]
It would be great if there was a setting on the Action Sheet to make it automatically hide when the user taps inside it. Actually it seems to me that this should really be default behavior.

If there is an actionable item inside an Action Sheet, I think the user would expect the sheet to go away when they click it. At that point they're done with the sheet.

**Comment by soumak77** [comment]
@cjh79 if I remember correctly, you should be able to place a `ba-close` attribute on any link you want to have close the actionsheet.  Using `ba-close` without specifying a value will cause the framework to close the nearest component, which should be the actionsheet.

**Comment by cjh79** [comment]
Oh, you're totally right, that does work. The one thing I didn't try. Excellent, thank you. As far as I'm concerned this resolves this issue.

Interestingly, I'd tried `ba-close-all`, and that does not seem to work on action sheets. It seems that the action sheet doesn't come up in `document.querySelectorAll('.is-active[ba-closable]')`.
