### ISSUE TITLE
Sass compilation error with v2.0.11

### ISSUE THREAD

**Issue by mattgd** [base-apps/angular-base-apps#97]
Hi there! I'm running into an error when trying to compile the Sass files for Base Apps.

* I installed angular-base-apps using npm: `npm install angular-base-apps --save` and am using version **2.0.11**.
* The Sass version I have installed is **Sass 3.5.5 (Bleeding Edge)** (via `sass -v`).

When trying to compile the Sass from the `scss` directory, I get the following output:
```
$ sass base.scss
Error: $original: "." is not a valid selector: Invalid CSS after ".": expected class name, was "" for `selector-replace'
        on line 26 of vendor/spinkit/spinners/4-wandering-cubes.scss, in `sk-wandering-cubes-animation'
        from line 49 of helpers/_loaders.scss, in `size-loaders'
        from line 93 of components/_button.scss, in `button-size'
        from line 283 of components/_button.scss, in `button'
        from line 290 of components/_button.scss, in `@content'
        from line 49 of helpers/_functions.scss, in `exports'
        from line 288 of components/_button.scss
        from line 30 of base.scss
  Use --trace for backtrace.
```

This happens on my system without modifying any of the Sass files.

Line 26 being referenced in `vendor/spinkit/spinners/4-wandering-cubes.scss`, which is in the `sk-wandering-cubes-animation` mixin:
```
$keyframeName: selector-replace("sk-wanderingCube-" + $width + "-" + $height, ".", "");
```
Sass wants a class name after the "." and in the empty quotes.

Any ideas on what the issue could be? Let me know what additional information you may need. Thanks in advance!

**Comment by soumak77** [comment]
@mattgd seems similar to https://github.com/base-apps/angular-base-apps/issues/91.  Try the solution mentioned in that issue.

**Comment by mattgd** [comment]
@soumak77 Disabling loaders as instructed in #91 did the trick. Thanks a lot!
