### ISSUE TITLE
active-true not firing in IE Edge (15 & 16)

### ISSUE THREAD

**Issue by mattgrande** [base-apps/angular-base-apps#98]
Has anyone else noticed that the `active-true` event no longer fires in IE Edge v15+ (14 worked fine)? I'm listening for when a modal is fully open, and the active-true has stopped working...

**Comment by soumak77** [comment]
@mattgrande what version of the framework are you using?  The event was originally named `active-true`, but was later changed.  See most recent docs regarding `animateAndAdvise ` and `ba-advise`: http://base-apps.github.io/angular-base-apps/latest/#!/angular-modules

**Comment by mattgrande** [comment]
Oh crap, I got my apps confused; This one is using Foundation For Apps still :/

Closing!
